version: '3'

services:
  
  backend:
    restart: always
    build: backend
    ports:
      - 5000
    volumes:
      - /home/mario/tools/smart_plugs/config.json:/app/config.json:ro
    networks:
      - smart_plug_network
  
  frontend:
    restart: always
    build: frontend
    ports:
      - "8082:3000"
    environment:
      BACKEND_URL: http://backend:5000
      NODE_ENV: development
    networks:
      - smart_plug_network

networks:
  smart_plug_network: