version: '3'

services:
  
  backend:
    build: backend
    ports:
      - "5000"
    environment:
      CONFIG_PATH: "/home/mario/tools/smart_plugs/config.json"
    command: ["uvicorn", "--host", "0.0.0.0", "--port", "5000", "main:app"]

    networks:
      - smart_plug_network
  
  frontend:
    build: frontend
    ports:
      - "5001:3000"
    environment:
      BACKEND_URL: "http://backend:5000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - smart_plug_network

networks:
  smart_plug_network: