version: '3'

services:
  
  backend:
    build: backend
    ports:
      - "5000:5000"
    command: ["uvicorn", "--host", "0.0.0.0", "--port", "5000", "main:app"]
    networks:
      - smart_plug_network
  
  frontend:
    build: frontend
    ports:
      - "5001:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - smart_plug_network

networks:
  smart_plug_network: