version: '3'

services:
  
  backend:
    image: python:3.12.2-slim
    build: backend
    ports:
      - "5000"
    environment:
      BACKEND_PORT: 5000
    volumes:
      - /home/mario/tools/smart_plugs/config.json:/app/config.json:ro

    networks:
      - smart_plug_network
  
  frontend:
    image: node:20.11.0-alpine
    build: frontend
    ports:
      - "8082:3000"
    environment:
      BACKEND_URL: $BACKEND_URL
    networks:
      - smart_plug_network

networks:
  smart_plug_network: