version: '3'

services:
  
  backend:
    build: backend
    ports:
      - "5000"
    environment:
      CONFIG_PATH: $CONFIG_PATH
    command: ["uvicorn", "--host", "0.0.0.0", "--port", "5000", "main:app"]

    networks:
      - smart_plug_network
  
  frontend:
    build: frontend
    ports:
      - "5001:3000"
    environment:
      BACKEND_URL: $BACKEND_URL
    networks:
      - smart_plug_network

networks:
  smart_plug_network: