version: '3'

services:
  
  backend:
    restart: always
    build:
      context: backend
      args:
        CONFIG_FILE_LOCATION: config.json
    ports:
      - 5000
    networks:
      - smart_plug_network
  
  frontend:
    restart: always
    build:
      context: frontend
    ports:
      - "8082:3000"
    environment:
      BACKEND_URL: http://backend:5000
      NODE_ENV: development
    networks:
      - smart_plug_network

networks:
  smart_plug_network: